# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8caaf4bf61e511b217543912b883cd86e1132215c9a8e4523d2e1c58e539d3e48ac452defcbe74caf10b5fcbf02a6ffb097a9f988159b520d3013b2b73a8dee8

test:
  secret_key_base: 0faf700ec0bae5719e401932431a2c1d6719364144388ab56a39c4c8ed7fc84dca321e2be1fe558236cc3b6b23fbae5810b5fdd2b489e96ed69501b0bc55bde3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
